artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/malaria_cell_images_dataset.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data
